In [21]:
from sklearn.cluster import KMeans
from PIL import Image
import random
import numpy as np


CLUSTERS_COUNT = 3

img = Image.open('Lenna.png')

l = np.array(img.getdata())

kmeans = KMeans(n_clusters=CLUSTERS_COUNT, random_state = 0).fit(l)

centers = kmeans.cluster_centers_
colors = kmeans.predict(l)

print(colors)
print(centers)

for i in range(len(l)):
    l[i] = centers[colors[i]]

print(l.shape)


l = np.array([l], dtype=np.uint8)
l.resize(*img.size, 3)


res = Image.fromarray(l)
res.show()
res.save('result.png')

[2 2 2 ... 0 0 0]
[[195.52450266  98.32275724 101.12015844]
 [109.89984625  34.36117992  71.83259304]
 [225.12109438 167.51585883 148.12551152]]
(262144, 3)
